"""
Highly divisible triangular number
   
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math

def get_triangular_number(x):
    return int(x*(x+1)/2)

def get_divisors(x):
    divisors = [x]
    for i in range(1, int( math.sqrt(x))+1):
        if x%i == 0:
            divisors.append(i)
    return divisors

n = 1
while True:
    traingular_number = get_triangular_number(n)
    divisors = get_divisors(traingular_number)
    print(traingular_number, len(divisors))
    if len(divisors) > 500:
        print(traingular_number)
        break
    n += 1